name: Deploy Application

on:
  push:
    branches: ['production']

jobs:
  create-deployment-artifacts:
    name: Create Deployment artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, gmp
      - name: Composer install
        run: |
          composer install --no-dev --no-interaction --prefer-dist
